---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
# icons found here https://github.com/walkxcode/dashboard-icons

- Containers:
    - Portainer:
        icon: portainer.svg
        href: "https://{{portainer_host}}"
        description: docker
        widget:
          type: portainer
          url: "https://portainer:9443"
          env: 2
          key: "{{ portainer_api_key }}"
- Network:
    - Adguard:
        icon: adguard.svg
        href: "https://{{adguard_host}}"
        description: adguard
        widget:
          type: adguard
          url: http://adguard-unbound-doh
          username: admin
          password: password
- Other:
    - GitHub:
        icon: github.svg
        href: https://github.com
        description: source code
