---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
# icons found here https://github.com/walkxcode/dashboard-icons

- Containers:
    - Portainer:
        icon: portainer.svg
        href: "{{ portainer_host }}"
        description: docker
        widget:
          type: portainer
          url: "{{ portainer_host }}"
          env: 1
          key: "{{ portainer_api_key }}"
- Network:
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href: "{{ uptime_kuma_host }}"
        description: internal
        widget:
          type: uptimekuma
          url: "{{ uptime_kuma_host }}"
          slug: home
- Other:
    - GitHub:
        icon: github.svg
        href: https://github.com
        description: source code
