---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
# icons found here https://github.com/walkxcode/dashboard-icons

- Resources:
    - Portainer:
        icon: portainer.svg
        href: "https://{{ portainer_host }}"
        widget:
          type: portainer
          url: "https://portainer:9443"
          env: 2
          key: "{{ portainer_api_key }}"
    - Watchtower:
        widget:
          type: watchtower
          url: "http://watchtower:8080"
          key: "{{ watchtower_token }}"
    - Grafana:
        icon: grafana.svg
        href: "https://{{ grafana_host }}"
        widget:
          type: grafana
          url: "http://grafana:3000"
          username: admin
          password: "{{ grafana_password }}"
    - UptimeKuma:
        icon: uptime-kuma.png
        href: "https://{{ uptime_kuma_host }}"
        widget:
          type: uptimekuma
          url: http://uptime_kuma:3001
          slug: server
- Network:
    - Adguard:
        icon: adguard-home.svg
        href: "https://{{ adguard_host }}"
        widget:
          type: adguard
          url: http://adguard-unbound-doh:3000
          username: admin
          password: "{{ adguard_password }}"
    - Traefik:
        icon: traefik.svg
        href: "https://{{ traefik_host }}"
        widget:
          type: traefik
          url: http://traefik:8080
          username: user
          password: "{{ traefik_password }}"
    - Wireguard:
        icon: wireguard.svg
        href: "https://{{ wireguard_host }}"
        widget:
          type: wgeasy
          url: http://wg-easy:51821
          username: user
          password: "{{ wireguard_password }}"
- Other:
    - Changedetect:
        icon: changedetection-io.svg
        href: "https://{{ changedetect_host }}"
        widget:
          type: changedetectionio
          url: http://changedetect:4000
          password: "{{ changedetection_api_key }}"
    - GitHub:
        icon: github.svg
        href: https://github.com
