---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
# icons found here https://github.com/walkxcode/dashboard-icons

- Resources:
    - Portainer:
        icon: portainer.svg
        href: "https://{{ portainer_host }}"
        description: docker
        widget:
          type: portainer
          url: "https://portainer:9443"
          env: 2
          key: "{{ portainer_api_key }}"
    - Grafana:
        icon: grafana.svg
        href: "https://{{ grafana_host }}"
        description: grafana
        widget:
          type: grafana
          url: "https://grafana:3000"
          username: admin
          password: "{{ grafana_password }}"
    - WgEasy:
        icon: uptimekuma.svg
        href: "https://{{ uptime_kuma_host }}"
        description: uptimekuma
        widget:
          type: uptimekuma
          url: http://uptime_kuma
          slug: server
- Network:
    - Adguard:
        icon: adguard.svg
        href: "https://{{ adguard_host }}"
        description: adguard
        widget:
          type: adguard
          url: http://adguard-unbound-doh:3000
          username: admin
          password: "{{ adguard_password }}"
    - Traefik:
        icon: traefik.svg
        href: "https://{{ traefik_host }}"
        description: traefik
        widget:
          type: traefik
          url: http://traefik:8080
          username: user
          password: "{{ traefik_password }}"
    - WgEasy:
        icon: wg-easy.svg
        href: "https://{{ wireguard_host }}"
        description: wg-easy
        widget:
          type: wg-easy
          url: http://wg-easy:51821
          username: user
          password: "{{ wireguard_password }}"
- Other:
    - GitHub:
        icon: github.svg
        href: https://github.com
        description: source code
