title: Deniz Homepage
startUrl: https://denizozogul.com
theme: dark

NetworkManagement:
  - Portainer (Homelab):
      icon: portainer.png
      href: https://10.8.2.7
      description: Docker Container Management
      server: my-docker
      container: portainer
      widget:
        type: portainer
        url: https://10.8.2.7
        env: 1
        key: KEY
