---
title: Deniz Homepage
startUrl: https://denizozogul.com
theme: dark
headerStyle: clean
cardBlur: md
color: zinc
fiveColumns: true
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: false
