---
- name: Create the dockerproxy network
  community.general.docker_network:
    name: dockerproxy
    state: present

- name: Make sure the dockerproxt container is created and running
  register: dockerproxy_result
  retries: 5
  until: dockerproxy_result is succeeded
  community.general.docker_container:
    name: "dockerproxy"
    image: "ghcr.io/tecnativa/docker-socket-proxy:{{ dockerproxy_version }}"
    pull: yes
    env:
      "CONTAINERS": "1"
      "SERVICES": "1"
      "TASKS": "1"
      "POST": "0"
    ports:
      - 127.0.0.1:2375:2375
    networks:
      - name: dockerproxy
    state: "started"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart_policy: unless-stopped
