---
- name: Make sure Watchtower is created and running
  register: watchtower_result
  retries: 5
  until: watchtower_result is succeeded
  community.general.docker_container:
    name: "watchtower"
    image: "containrrr/watchtower"
    pull: yes
    state: "started"
    env:
      WATCHTOWER_CLEANUP: "true"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - name: homelab
    restart_policy: unless-stopped
