---
- name: Make sure Watchtower is created and running
  register: watchtower_result
  retries: 5
  until: watchtower_result is succeeded
  community.general.docker_container:
    name: "watchtower"
    image: "containrrr/watchtower"
    pull: yes
    state: "started"
    env:
      WATCHTOWER_CLEANUP: "true"
      DOCKER_HOST: "tcp://socket-proxy:2375"
    networks:
      - name: homelab
        ipv4_address: 10.8.2.21
      - name: socket_proxy
    restart_policy: unless-stopped
