---
- name: Make sure the Homepage container is created and running
  register: picoshare_result
  retries: 5
  until: picoshare_result is succeeded
  community.general.docker_container:
    name: "picoshare"
    image: "mtlynch/picoshare:{{ picoshare_version }}"
    pull: yes
    env:
      PORT: "4001"
      PS_SHARED_SECRET: "{{ picoshare_shared_secret }}"
    networks:
      - name: homelab
        ipv4_address: 10.8.2.12
    command: -db /data/store.db
    state: "started"
    volumes:
      - "{{ docker_dir }}/picoshare:/data"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.picoshare.entrypoints: "http"
      traefik.http.routers.picoshare.rule: "Host(`{{ picoshare_host }}`)"
      traefik.http.middlewares.picoshare-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.picoshare.middlewares: "picoshare-https-redirect"
      traefik.http.routers.picoshare-secure.entrypoints: "https"
      traefik.http.routers.picoshare-secure.rule: "Host(`{{ picoshare_host }}`)"
      traefik.http.routers.picoshare-secure.tls: "true"
      traefik.http.routers.picoshare-secure.service: "picoshare"
      traefik.http.services.picoshare.loadbalancer.server.port: "4001"
      traefik.docker.network: "homelab"
