---
- name: Make sure the changedetect container is created and running
  register: changedetect_result
  retries: 5
  until: changedetect_result is succeeded
  community.general.docker_container:
    name: "changedetect"
    image: "dgtlmoon/changedetection.io:{{ changedetect_version }}"
    pull: yes
    networks:
      - name: homelab
        ipv4_address: 10.8.2.9
    state: "started"
    volumes:
      - "{{ docker_dir }}/datastore"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.changedetect.entrypoints: "http"
      traefik.http.routers.changedetect.rule: "Host(`{{ changedetect_host }}`)"
      traefik.http.middlewares.changedetect-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.changedetect.middlewares: "changedetect-https-redirect,ipwhitelist"
      traefik.http.routers.changedetect-secure.entrypoints: "https"
      traefik.http.routers.changedetect-secure.rule: "Host(`{{ changedetect_host }}`)"
      traefik.http.routers.changedetect-secure.tls: "true"
      traefik.http.routers.changedetect-secure.service: "changedetect"
      traefik.http.routers.changedetect-secure.middlewares: "authelia@docker"
      traefik.http.services.changedetect.loadbalancer.server.port: "5000"
      traefik.docker.network: "homelab"