---
- name: Make sure the changedetect container is created and running
  register: changedetect_result
  retries: 5
  until: changedetect_result is succeeded
  community.general.docker_container:
    name: "changedetect"
    image: "dgtlmoon/changedetection.io:{{ changedetect_version }}"
    pull: yes
    networks:
      - name: wg_network
        ipv4_address: 10.8.2.9
    state: "started"
    volumes:
      - "{{ docker_dir }}/datastore"
    restart_policy: unless-stopped
