---
- name: Create the Homepage directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/homepage"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0775"

- name: Template the Homepage settings
  ansible.builtin.template:
    src: "settings.yaml"
    dest: "{{ docker_dir }}/homepage/settings.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0775"

- name: Template the Homepage docker settings
  ansible.builtin.template:
    src: "docker.yaml"
    dest: "{{ docker_dir }}/homepage/docker.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0775"

- name: Make sure the Homepage container is created and running
  register: homepage_result
  retries: 5
  until: homepage_result is succeeded
  community.general.docker_container:
    name: "homepage"
    image: "ghcr.io/gethomepage/homepage:{{ homepage_version }}"
    pull: yes
    env:
      PUID: "1000"
      PGID: "1000"
    networks:
      - name: homelab
        ipv4_address: 10.8.2.11
    state: "started"
    volumes:
      - "{{ docker_dir }}/homepage:/app/config"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart_policy: unless-stopped
    labels:
      # HTTP Router for home.denizozogul.com
      traefik.enable: "true"
      traefik.http.routers.homepage.entrypoints: "http"
      traefik.http.routers.homepage.rule: "Host(`home.denizozogul.com`)"
      traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.homepage.middlewares: "homepage-https-redirect,mywwwremove,ipwhitelist"
      
      # HTTPS Router for home.denizozogul.com
      traefik.http.routers.homepage-secure.entrypoints: "https"
      traefik.http.routers.homepage-secure.rule: "Host(`home.denizozogul.com`)"
      traefik.http.routers.homepage-secure.tls: "true"
      traefik.http.routers.homepage-secure.service: "homepage"
      traefik.http.routers.homepage-secure.middlewares: "authelia@docker"
      
      # HTTP Router for www.denizozogul.com
      traefik.http.routers.homepage-www.entrypoints: "http"
      traefik.http.routers.homepage-www.rule: "Host(`www.denizozogul.com`)"
      traefik.http.routers.homepage-www.middlewares: "homepage-https-redirect,mywwwremove,ipwhitelist"
      
      # HTTPS Router for www.denizozogul.com
      traefik.http.routers.homepage-secure-www.entrypoints: "https"
      traefik.http.routers.homepage-secure-www.rule: "Host(`www.denizozogul.com`)"
      traefik.http.routers.homepage-secure-www.tls: "true"
      traefik.http.routers.homepage-secure-www.service: "homepage"
      traefik.http.routers.homepage-secure-www.middlewares: "authelia@docker"
      
      # Service
      traefik.http.services.homepage.loadbalancer.server.port: "3000"

