---
- name: Create the Homepage directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/homepage"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0775"

- name: Template the Homepage settings
  ansible.builtin.template:
    src: "settings.yaml"
    dest: "{{ docker_dir }}/homepage/settings.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0664"

- name: Template the Homepage widgets
  ansible.builtin.template:
    src: "widgets.yaml"
    dest: "{{ docker_dir }}/homepage/widgets.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0664"

- name: Template the Homepage bookmarks
  ansible.builtin.template:
    src: "bookmarks.yaml"
    dest: "{{ docker_dir }}/homepage/bookmarks.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0664"

- name: Template the Homepage services
  ansible.builtin.template:
    src: "services.yaml"
    dest: "{{ docker_dir }}/homepage/services.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0664"

- name: Template the Homepage docker settings
  ansible.builtin.template:
    src: "docker.yaml"
    dest: "{{ docker_dir }}/homepage/docker.yaml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0664"
# burada bir hata aldım. chmode 0664 yapınca düzeldi
- name: Make sure the Homepage container is created and running
  register: homepage_result
  retries: 5
  until: homepage_result is succeeded
  community.general.docker_container:
    name: "homepage"
    image: "ghcr.io/gethomepage/homepage:{{ homepage_version }}"
    pull: yes
    security_opts:
      - no-new-privileges:true
    networks:
      - name: homelab
        ipv4_address: 10.8.2.11
    state: "started"
    volumes:
      - "{{ docker_dir }}/homepage:/app/config"
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.homepage.entrypoints: "http"
      traefik.http.routers.homepage.rule: "Host(`{{ homepage_host }}`)"
      traefik.http.middlewares.homepage-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.homepage.middlewares: "homepage-https-redirect,ipwhitelist"
      traefik.http.routers.homepage-secure.entrypoints: "https"
      traefik.http.routers.homepage-secure.rule: "Host(`{{ homepage_host }}`)"
      traefik.http.routers.homepage-secure.tls: "true"
      traefik.http.routers.homepage-secure.service: "homepage"
      traefik.http.routers.homepage-secure.middlewares: "authelia@docker"
      traefik.http.services.homepage.loadbalancer.server.port: "3000"
      traefik.docker.network: "homelab"
