---
- name: Make sure the Vaultwarden container is created and running
  register: vaultwarden_result
  retries: 5
  until: vaultwarden_result is succeeded
  community.general.docker_container:
    name: "vaultwarden"
    image: "vaultwarden/server:{{ vaultwarden_version }}"
    pull: yes
    networks:
      - name: homelab
        ipv4_address: 10.8.2.6
    state: "started"
    labels:
      traefik.enable: "true"
      traefik.http.routers.vault.entrypoints: "http"
      traefik.http.routers.vault.rule: "Host(`{{ vaultwarden_host }}`)"
      traefik.http.middlewares.vault-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.vault.middlewares: "vault-https-redirect,ipwhitelist"
      traefik.http.routers.vault-secure.entrypoints: "https"
      traefik.http.routers.vault-secure.rule: "Host(`{{ vaultwarden_host }}`)"
      traefik.http.routers.vault-secure.tls: "true"
      traefik.http.routers.vault-secure.service: "vault"
      traefik.http.routers.vault-secure.middlewares: "authelia@docker"
      traefik.http.services.vault.loadbalancer.server.port: "80"
      traefik.docker.network: "homelab"
      # homepage.name: "Vaultwarden"
      # homepage.icon: "https://raw.githubusercontent.com/dani-garcia/vaultwarden/master/resources/vaultwarden-icon.svg"
      # hompage.href: "https://{{ vaultwarden_host }}"

    ports:
      - "{{ vaultwarden_port }}:3012"
    volumes:
      - "{{ docker_dir }}/vw-data:/data"
    restart_policy: unless-stopped
