- name: Ensure the Portainer container is created and running
  register: portainer_result
  retries: 5
  until: portainer_result is succeeded
  community.general.docker_container:
    name: "portainer"
    image: "portainer/portainer-ce:{{ portainer_version }}"
    pull: yes
    networks:
      - name: homelab
        ipv4_address: 10.8.2.7
    state: "started"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ docker_dir }}/portainer_data:/data"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: "http"
      traefik.http.routers.portainer.rule: "Host(`{{ portainer_host }}`)"
      traefik.http.middlewares.portainer-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.portainer.middlewares: "portainer-https-redirect,ipwhitelist"
      traefik.http.routers.portainer-secure.entrypoints: "https"
      traefik.http.routers.portainer-secure.rule: "Host(`{{ portainer_host }}`)"
      traefik.http.routers.portainer-secure.tls: "true"
      traefik.http.routers.portainer-secure.service: "portainer"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
      traefik.docker.network: "homelab"
