---
- name: Make sure the mywebsite container is created and running
  register: mywebsite_result
  retries: 5
  until: mywebsite_result is succeeded
  community.general.docker_container:
    name: "mywebsite"
    image: "874521/denizozogulsite:{{ mywebsite_version }}"
    pull: yes
    networks:
      - name: homelab
        ipv4_address: 10.8.2.10
    state: "started"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.mywebsite.entrypoints: "http"
      traefik.http.routers.mywebsite.rule: "Host(`{{ root_host }}`)"
      traefik.http.routers.mywebsite.rule: "Host(`{{ root_host }}`) || Host(`www.{{ root_host }}`)"
      traefik.http.routers.mywebsite-secure.rule: "Host(`{{ root_host }}`) || Host(`www.{{ root_host }}`)"
      traefik.http.middlewares.mywebsite-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.mywebsite.middlewares: "mywebsite-https-redirect,mywwwremove"
      traefik.http.routers.mywebsite-secure.entrypoints: "https"
      traefik.http.routers.mywebsite-secure.tls: "true"
      traefik.http.routers.mywebsite-secure.service: "mywebsite"
      traefik.http.services.mywebsite.loadbalancer.server.port: "8080"
      traefik.docker.network: "homelab"
