---
- name: Make sure the mywebsite container is created and running
  register: mywebsite_result
  retries: 5
  until: mywebsite_result is succeeded
  community.general.docker_container:
    name: "mywebsite"
    image: "874521/denizozogulsite:{{ mywebsite_version }}"
    pull: yes
    networks:
      - name: wg_network
        ipv4_address: 10.8.2.10
    state: "started"
    restart_policy: unless-stopped
