---
- name: Make sure the privatebin container is created and running https://ppfeufer.de/privatebin-your-self-hosted-pastebin-instance/
  register: privatebin_result
  retries: 5
  until: privatebin_result is succeeded
  community.general.docker_container:
    name: "privatebin"
    image: "privatebin/nginx-fpm-alpine:{{ privatebin_version }}"
    pull: yes
    env:
      PUID: "1000"
      PGID: "1000"
    networks:
      - name: wg_network
        ipv4_address: 10.8.2.13
    state: "started"
    volumes:
      - "{{ docker_dir }}/privatebin/data:/srv/data"
      - "{{ docker_dir }}/privatebin/cfg/conf.php:/srv/cfg/conf.php:ro"
    restart_policy: unless-stopped
