---
- name: Create the PrivateBin config folders
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"
  loop:
    - privatebin/cfg
    - privatebin/data

- name: Template the PrivateBin conf.php file
  ansible.builtin.template:
    src: conf.php
    dest: "{{ docker_dir }}/privatebin/cfg/conf.php"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Make sure the privatebin container is created and running https://ppfeufer.de/privatebin-your-self-hosted-pastebin-instance/
  register: privatebin_result
  retries: 5
  until: privatebin_result is succeeded
  community.general.docker_container:
    name: "privatebin"
    image: "privatebin/nginx-fpm-alpine:{{ privatebin_version }}"
    pull: yes
    env:
      PUID: "1000"
      PGID: "1000"
    networks:
      - name: homelab
        ipv4_address: 10.8.2.13
    state: "started"
    volumes:
      - "{{ docker_dir }}/privatebin/data:/srv/data"
      - "{{ docker_dir }}/privatebin/cfg/conf.php:/srv/cfg/conf.php:ro"
    restart_policy: unless-stopped
    labels:
      traefik.enable: "true"
      traefik.http.routers.privatebin.entrypoints: "http"
      traefik.http.routers.privatebin.rule: "Host(`{{ privatebin_host }}`)"
      traefik.http.middlewares.privatebin-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.privatebin.middlewares: "privatebin-https-redirect"
      traefik.http.routers.privatebin-secure.entrypoints: "https"
      traefik.http.routers.privatebin-secure.rule: "Host(`{{ privatebin_host }}`)"
      traefik.http.routers.privatebin-secure.tls: "true"
      traefik.http.routers.privatebin-secure.service: "privatebin"
      traefik.http.services.privatebin.loadbalancer.server.port: "8080"
      traefik.docker.network: "homelab"
