---
- name: Create the v2ray directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/v2ray"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0775"

- name: Template the config
  ansible.builtin.template:
    src: "config.json"
    dest: "{{ docker_dir }}/v2ray/config.json"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0664"

- name: Install V2Ray server using Docker
  community.general.docker_container:
    name: "v2ray"
    image: "v2fly/v2fly-core"
    command: run -c /etc/v2ray/config.json
    pull: yes
    state: "started"
    restart_policy: unless-stopped
    volumes:
      - "{{ docker_dir }}/v2ray:/etc/v2ray"
    networks:
      - name: homelab
        ipv4_address: 10.8.2.5
    dns_servers:
      - 10.8.2.2
    env:
      V2RAY_VMESS_AEAD_FORCED: "false"
    labels:
      traefik.enable: "true"
      traefik.http.routers.api1.entrypoints: "https"
      traefik.http.routers.api1.tls.domains[0].main: "Host(`{{ v2ray_host }}`)"
      traefik.http.routers.api1.rule: PathPrefix(`/wsm`)
      traefik.http.routers.api1.tls: "true"
      traefik.http.routers.api1.service: api1
      traefik.http.services.api1.loadbalancer.server.port: "1000"
      traefik.http.routers.api2.entrypoints: "https"
      traefik.http.routers.api2.tls.domains[0].main: "Host(`{{ v2ray_host }}`)"
      traefik.http.routers.api2.rule: PathPrefix(`/wsl`)
      traefik.http.routers.api2.tls: "true"
      traefik.http.routers.api2.service: api2
      traefik.http.services.api2.loadbalancer.server.port: "1001"
