---
- name: Create the bw-universe network
  community.general.docker_network:
    name: bw-universe
    ipam_config:
      - subnet: 10.20.30.0/24
        gateway: 10.20.30.1

- name: Create the bw-docker network
  community.general.docker_network:
    name: bw-docker

- name: Create the bw-services network
  community.general.docker_network:
    name: bw-services

- name: Create the folders
  ansible.builtin.file:
    path: "{{ docker_dir }}/{{ item }}"
    state: directory
    owner: root
    group: 101
    mode: 0770
  loop:
    - bw-data/
    - bw-data/data

- name: Copy the env file
  ansible.builtin.template:
    src: env.j2
    owner: root
    group: 101
    mode: 0644
    dest: "{{ docker_dir }}/bw-data/.env"

- name: Run bunkerweb container
  community.general.docker_container:
    name: "bunkerweb"
    image: "bunkerity/bunkerweb:{{ bunkerweb_version }}"
    ports:
      - "80:8080"
      - "443:8443"
    labels:
      bunkerweb.INSTANCE: "yes"
    env_file: "{{ docker_dir }}/bw-data/.env"
    networks:
      - name: bw-universe
      - name: bw-services
      - name: wg_network
        ipv4_address: 10.8.2.5
    state: started
    restart_policy: unless-stopped

- name: Run bw-scheduler container
  community.general.docker_container:
    name: "bw-scheduler"
    image: "bunkerity/bunkerweb-scheduler:{{ bunkerweb_version }}"
    volumes:
      - bw-data:/data
    env:
      DOCKER_HOST: "tcp://bw-docker:2375"
    networks:
      - name: bw-universe
      - name: bw-docker
    state: started
    restart_policy: unless-stopped

- name: Run bw-docker container
  community.general.docker_container:
    name: bw-docker
    image: "tecnativa/docker-socket-proxy:{{ bw_docker_version }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env:
      CONTAINERS: "1"
      LOG_LEVEL: "warning"
    networks:
      - name: bw-docker
    state: started
    restart_policy: unless-stopped
