---
- name: Switch between encrypted and unencrypted DNS depending on the user choice
  ansible.builtin.set_fact:
    wireguard_dns: "10.8.2.2"

- name: Configure WireGuard to use Shadowsocks as a proxy
  community.general.docker_container:
    name: "wg-easy"
    image: "ghcr.io/wg-easy/wg-easy:{{ wg_easy_version }}"
    pull: yes
    networks:
      - name: homelab
        ipv4_address: 10.8.2.8
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
      "net.ipv4.ip_forward": "1"
    capabilities:
      - net_admin
      - sys_module
    state: "started"
    env:
      "WG_HOST": "{{ wireguard_host }}"
      "WG_DEFAULT_DNS": "{{ wireguard_dns }}"
      "WG_DEFAULT_ADDRESS": "{{ wireguard_subnet }}"
      "WG_PORT": "{{ wireguard_port }}"
      "WG_PERSISTENT_KEEPALIVE": "25"
      "WG_ALLOWED_IPS": "{{ wireguard_client_allowed_ips }}"
      "PASSWORD_HASH": "{{ wireguard_password_hash }}"
    ports:
      - "{{ wireguard_port }}:51820/udp"
    volumes:
      - "{{ docker_dir }}/wg-easy:/etc/wireguard"
    labels:
      traefik.enable: "true"
      traefik.http.routers.wg.entrypoints: "http"
      traefik.http.routers.wg.rule: "Host(`{{ wireguard_host }}`)"
      traefik.http.middlewares.wg-https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.wg.middlewares: "wg-https-redirect,ipwhitelist"
      traefik.http.routers.wg-secure.entrypoints: "https"
      traefik.http.routers.wg-secure.rule: "Host(`{{ wireguard_host }}`)"
      traefik.http.routers.wg-secure.tls: "true"
      traefik.http.routers.wg-secure.service: "wg"
      traefik.http.services.wg.loadbalancer.server.port: "51821"
      traefik.docker.network: "homelab"
    restart_policy: unless-stopped
